version: '3.9'
name: 'streaming'

services:
  auth:
    build: ./services/auth
    restart: unless-stopped
    ports:
      - "8082:8083"
    links:
      - redis
      - users-postgres
    command: python3 -u -m uvicorn main:app --host 0.0.0.0 --port 8083
  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
     - 6379
    volumes:
      - "redis:/data/cache"
  users-postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 256128
      POSTGRES_USER: postgres
      POSTGRES_DB: auth
    expose:
      - 5432
    volumes:
      - "postgres:/data/db"

volumes:
  redis:
  postgres:
